name: Build and publish rust builder image
on:
  push:
    branches: ["master"]
    # paths:
      # - 'rust/**'

  workflow_dispatch:

jobs:
  release-builder:
    permissions:
      contents: read
      packages: write

    uses: kea-run/builder/.github/workflows/_build-builder.yaml@master
    with:
      dockerhub_repo: kearun
      dir: rust
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
